title: Css-html -Frontend
description: Front End by html and css
template:
  repo: css-html-frontend-template
  name: css-html-frontend
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
